<h1><center> Régression Linéaire Simple, Multiple et Polynomiale avec Scikit-Learn </center></h1>


# Régression Linéaire Simple
<br><br>



## 1. Importez les bibliothéques necessaires 

In [33]:
import pandas as pd

from sklearn import model_selection, metrics
from sklearn.linear_model import LogisticRegression
 

## 2. Importez le jeu de données 'Salaire_Experience.csv'

In [34]:
df = pd.read_csv('Salaire_Experience.csv')
df.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

## 3. Notre variable target (Y) est le salaire, Récuprer X et Y à partir du jeu de données 

In [41]:
X = df.iloc[:,:1]
Y = df.iloc[:,-1:]
print(X.shape, Y.shape)

(30, 1) (30, 1)


## 4. Fractionnement le jeu de données en jeu d'entraînement et jeu de test (1/3 pour le test)

In [43]:

from sklearn import model_selection

#subdivision des données 
X_app,X_test,y_app,y_test = model_selection.train_test_split(X,Y,test_size = 1/3,random_state=0)

print(X_app.shape,X_test.shape,y_app.shape,y_test.shape)

(20, 1) (10, 1) (20, 1) (10, 1)


## 5. Créer votre modèle LinearRegression et entraînez le sur les données d'entraînement

In [50]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(solver="liblinear")

modele = lr.fit(X_app,y_app)

# coef_ : y=aX1+bX2+cX3... + z
# intercept_ : le b de y=ax+b, ou le z du coef_
print(modele.coef_,modele.intercept_)

[[-0.96094589]
 [-0.73864064]
 [-0.7735066 ]
 [-0.91436255]
 [-0.59117924]
 [-0.6312378 ]
 [-0.4981952 ]
 [-0.53091669]
 [-0.61751128]
 [-0.44839876]
 [-0.59117924]
 [-0.39535654]
 [-0.41230733]
 [-0.33380803]
 [-0.27434654]
 [-0.32673792]
 [-0.25639258]
 [-0.15886797]
 [-0.19694645]
 [-0.09619953]] [-0.00177072 -0.25139062 -0.20804688 -0.04909001 -0.45585302 -0.39673227
 -0.60466325 -0.55036882 -0.4167075  -0.69180327 -0.45585302 -0.79101574
 -0.75855791 -0.91526395 -1.0456365  -0.93021102 -1.08717111 -1.33219906
 -1.2324628  -1.50857193]


## 6. Predire les résultats du modèle sur l'ensemble du test

In [54]:
#prediction sur l'échantillon test
y_pred = modele.predict(X_test)

#utilisé pour les mesures de performances
from sklearn import metrics

#matrice de confusion
#confrontation entre Y obs. sur l’éch. test et la prédiction
cm = metrics.confusion_matrix(y_test,y_pred)
print(cm)

#taux de succès
acc = metrics.accuracy_score(y_test,y_pred)
print(acc) # 0.793 = (184 + 54)/ (184 + 17 + 45 + 54)

#taux d'erreur
err = 1.0 - acc
print(err) # 0.206 = 1.0 – 0.793

print(y_test)
print(y_pred)
#sensibilité (ou rappel) None, 'micro', 'macro', 'weighted
se = metrics.recall_score(y_test,y_pred)
print(se) 

[[0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0]]
0.0
1.0
      Salary
2    37731.0
28  122391.0
13   57081.0
10   63218.0
26  116969.0
24  109431.0
27  112635.0
11   55794.0
17   83088.0
22  101302.0
[ 54445. 121872. 121872. 121872. 121872. 121872. 121872. 121872. 121872.
 121872.]


ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].

## 7. Visualisation des résultats du modèle sur les données d'entraînement

## 8. Visualisation des résultats du modèle sur les données de test

## 9. Evaluez votre modèle par le mean_squared_error et mean_absolute_error

<br><br>
# Régression Linéaire Multiple
<br><br>


## 1. Importez le jeu de données 'Startups.csv'

In [55]:
df = pd.read_csv('Startups.csv')
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

##  2. Notre variable target (Y) est le profit, Récuprer X et Y à partir du jeu de données 

In [59]:
X = df.iloc[:,:-1]
Y = df.iloc[:,-1:]
print(X.shape, Y.shape)

(50, 4) (50, 1)


## 3. Encoder les variables qualitatives

In [63]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(df["State"])
list(le.classes_)

['California', 'Florida', 'New York']

In [ ]:
#>>> le.transform(["tokyo", "tokyo", "paris"])
#array([2, 2, 1]...)
#>>> list(le.inverse_transform([2, 2, 1]))
#['tokyo', 'tokyo', 'paris']

## 4. Fractionnement le jeu de données en jeu d'entraînement et jeu de test (20% pour le test)

In [65]:

from sklearn import model_selection

#subdivision des données 
X_app,X_test,y_app,y_test = model_selection.train_test_split(X,Y,test_size = 20/100,random_state=0)

print(X_app.shape,X_test.shape,y_app.shape,y_test.shape)

(40, 4) (10, 4) (40, 1) (10, 1)


## 5. Standariser les variables d'entrainement et de test

## 6. Créer votre modèle LinearRegression multiple et entraînez le sur les données d'entraînement

In [66]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(solver="liblinear")

modele = lr.fit(X_app,y_app)

# coef_ : y=aX1+bX2+cX3... + z
# intercept_ : le b de y=ax+b, ou le z du coef_
print(modele.coef_,modele.intercept_)

ValueError: could not convert string to float: 'California'

## 7. Predire les résultats du modèle sur l'ensemble du test

## 8. Visualisation des résultats du modèle sur les données d'entraînement en 3D avec les deux variable R&D Spend et Marketing Spend

## 9. Visualisation des résultats du modèle sur les données de test en 3D avec les deux variable R&D Spend et Marketing Spend

## 10. Evaluez votre modèle par le mean_squared_error


<br><br>
# Régression Polynomiale
<br><br>

## 1. Importez le jeu de données 'Salaire_Level.csv'

## 2. Notre variable target (Y) est le salaire, Récuprer X et Y à partir du jeu de données 

## 3. Créer votre modèle LinearRegression et entraînez le sur le jeu de données

## 4. Visualisation des résultats du modèle LinearRegression sur le jeu de données

## 5. Créer votre modèle Regression polynomiale et entraînez le sur le jeu de données, essayer avec différentes valeurs pour le degré (1..5). Visualiser dans la même figure les rélutats du modèle pour les différents degrés. Quelle est la meilleure valeur pour le degré ?

## 6. Faire la prédiction de la valeur 6 avec le modèle de régression linéaire simple et de régression polynomiale, qu'est ce que vous remarquez ?
